version: '3'

services:
  # Django приложение
  web:
    build:
      context: .
      args:
        BASE_IMAGE: ${BASE_IMAGE}
    container_name: my_iot_api_dev
    volumes:
      - .:/app
    ports:
      - "21000:20000" 
    depends_on:
      - db_dev
    env_file:
      - .dev.env 
    networks:
      - my_iot_api_dev

  # База данных PostgreSQL для dev
  db_dev:
    image: postgres:13
    container_name: my_iot_api_db_dev
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    env_file:
      - .dev.env
    networks:
      - my_iot_api_dev

volumes:
  postgres_data_dev:

networks:
  my_iot_api_dev:
    driver: bridge
