version: '3'

services:
  # Django приложение
  web:
    build: .
    container_name: my_super_api
    volumes:
      - .:/app
    ports:
      - "20000:20000"
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - my_super_api

  # База данных PostgreSQL
  db:
    image: postgres:13
    container_name: my_super_api_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydatabase
    env_file:
      - .env
    networks:
      - my_super_api

  # Сервер Nginx
  nginx:
    image: nginx:latest
    container_name: my_super_api_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "20001:80"
    depends_on:
      - web
    networks:
    - my_super_api

volumes:
  postgres_data:

networks:
  my_super_api:
    driver: bridge