version: '3'

services:
  # Django приложение
  web:
    build:
      context: .
      args:
        BASE_IMAGE: ${BASE_IMAGE}
    container_name: my_iot_api_dev
    volumes:
      - .:/app
    ports:
      - "21000:20000" 
    depends_on:
      - db_dev
    env_file:
      - .env 
    networks:
      - my_iot_api_dev

  # База данных PostgreSQL для dev
  db_dev:
    image: postgres:13
    container_name: my_iot_api_db_dev
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - my_iot_api_dev

  front:
    container_name:  my_iot_api_front_dev
    build:
      context: ..
      dockerfile: ManagerHomeAPI/Dockerfile.front
    ports:
      - "13000:3000"
    volumes:
      - ../front:/app/
    networks:
      - my_iot_api_dev

  # Сервер Nginx
  nginx:
    image: nginx:latest
    container_name: my_iot_api_nginx_dev
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "30000:80"
    depends_on:
      - web
    networks:
      - my_iot_api_dev

volumes:
  postgres_data_dev:

networks:
  my_iot_api_dev:
    driver: bridge
