version: '3'

services:
  # Django приложение
  web:
    build:
      context: .
      args:
        BASE_IMAGE: ${BASE_IMAGE}
    container_name: my_iot_api
    ports:
      - "20000:20000"
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - my_iot_api

  # База данных PostgreSQL
  db:
    image: postgres:13
    container_name: my_iot_api_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - my_iot_api

  # Сервер Nginx
  nginx:
    image: nginx:latest
    container_name: my_iot_api_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "20001:80"
    depends_on:
      - web
    networks:
    - my_iot_api

volumes:
  postgres_data:

networks:
  my_iot_api:
    driver: bridge