# Generated by Django 4.2.9 on 2024-01-09 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YandexAPI', '0002_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
